# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-20 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_author_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='fav_by',
            field=models.ManyToManyField(related_name='users', to='quotes.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='bob', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quote',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='quotes.User'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
